import { Geist, Geist_Mono } from "next/font/google";
import { Maven_Pro } from 'next/font/google';
import "./globals.css";
import { AuthContextProvider } from "./contexts/AuthContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mavenPro = Maven_Pro({
  variable: '--font-maven-pro',
  subsets: ['latin'],
});

export const metadata = {
  title: "Tune Buddy",
  description: "Generated by ME HAHAHAHAHAHAHA",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mavenPro.variable} antialiased`}
      >
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
